version: '3.8'

services:
  ad-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: ad-site
    ports:
      - "${PORT:-5201}:${PORT:-5201}"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - PORT=${PORT:-5201}
    restart: unless-stopped
    env_file:
      - .env
